look for window

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -69,19 +69,31 @@ jobs:
         echo "Waiting for device 45 sec..."
         sleep 45
         
-        while
+        while [[ ${EMU_BOOTED} != "1" ]];do
             echo "Waiting android to boot 10 sec..."
             sleep 10
-            EMU_BOOTED=`adb shell 'getprop sys.boot_completed'`
-            echo "getprop sys.boot_complete=$EMU_BOOTED"
-            n=$((n + 1))
-            if [ $n -gt 30 ]; then
-                echo "Android Emulator does not start in 5 minutes"
-                echo "failed" > /tmp/failed
-                exit 2
-            fi
-           [[ ${EMU_BOOTED} != *"1"* ]]
-           do :
+            CURRENT_FOCUS=`adb shell dumpsys window windows 2>/dev/null | grep -i mCurrentFocus`
+            echo "(DEBUG) Current focus: ${CURRENT_FOCUS}"
+
+            case $CURRENT_FOCUS in
+            *"Launcher"*)
+              EMU_BOOTED=1
+            ;;
+            *"Not Responding"*)
+              echo "System UI isn't responding ..."
+              adb shell input keyevent KEYCODE_DPAD_DOWN
+              adb shell input keyevent KEYCODE_DPAD_DOWN
+              adb shell input keyevent KEYCODE_ENTER
+            ;;
+            *)
+              n=$((n + 1))
+              if [ $n -gt 30 ]; then
+                  echo "Android Emulator does not start in 5 minutes"
+                  echo "failed" > /tmp/failed
+                  exit 2
+              fi
+            ;;
+            esac
         done
         echo "Android Emulator started."
         
